image:
  file: .gitpod.Dockerfile

ports:
  - port: 19000
    onOpen: open-browser
  - port: 19001
    onOpen: open-browser
  - port: 19002
    onOpen: open-browser

tasks:
  - init: npm install expo-cli --global
    init: npm install

